[{
    names: ["soccer"],
    surrogates: "⚽"
}, {
    names: ["basketball"],
    surrogates: "🏀"
}, {
    names: ["football"],
    surrogates: "🏈"
}, {
    names: ["baseball"],
    surrogates: "⚾"
}, {
    names: ["tennis"],
    surrogates: "🎾"
}, {
    names: ["volleyball"],
    surrogates: "🏐"
}, {
    names: ["rugby_football"],
    surrogates: "🏉"
}, {
    names: ["8ball"],
    surrogates: "🎱"
}, {
    names: ["golf"],
    surrogates: "⛳"
}, {
    names: ["golfer"],
    surrogates: "🏌"
}, {
    names: ["ping_pong"],
    surrogates: "🏓"
}, {
    names: ["badminton"],
    surrogates: "🏸"
}, {
    names: ["hockey"],
    surrogates: "🏒"
}, {
    names: ["field_hockey"],
    surrogates: "🏑"
}, {
    names: ["cricket"],
    surrogates: "🏏"
}, {
    names: ["ski"],
    surrogates: "🎿"
}, {
    names: ["skier"],
    surrogates: "⛷"
}, {
    names: ["snowboarder"],
    surrogates: "🏂",
    hasDiversity: !0
}, {
    names: ["ice_skate"],
    surrogates: "⛸"
}, {
    names: ["bow_and_arrow"],
    surrogates: "🏹"
}, {
    names: ["fishing_pole_and_fish"],
    surrogates: "🎣"
}, {
    names: ["rowboat"],
    surrogates: "🚣",
    hasDiversity: !0
}, {
    names: ["swimmer"],
    surrogates: "🏊",
    hasDiversity: !0
}, {
    names: ["surfer"],
    surrogates: "🏄",
    hasDiversity: !0
}, {
    names: ["bath"],
    surrogates: "🛀",
    hasDiversity: !0
}, {
    names: ["basketball_player"],
    surrogates: "⛹",
    hasDiversity: !0
}, {
    names: ["lifter"],
    surrogates: "🏋",
    hasDiversity: !0
}, {
    names: ["bicyclist"],
    surrogates: "🚴",
    hasDiversity: !0
}, {
    names: ["mountain_bicyclist"],
    surrogates: "🚵",
    hasDiversity: !0
}, {
    names: ["horse_racing"],
    surrogates: "🏇",
    hasDiversity: !0
}, {
    names: ["levitate"],
    surrogates: "🕴"
}, {
    names: ["trophy"],
    surrogates: "🏆"
}, {
    names: ["running_shirt_with_sash"],
    surrogates: "🎽"
}, {
    names: ["medal"],
    surrogates: "🏅"
}, {
    names: ["military_medal"],
    surrogates: "🎖"
}, {
    names: ["reminder_ribbon"],
    surrogates: "🎗"
}, {
    names: ["rosette"],
    surrogates: "🏵"
}, {
    names: ["ticket"],
    surrogates: "🎫"
}, {
    names: ["tickets"],
    surrogates: "🎟"
}, {
    names: ["performing_arts"],
    surrogates: "🎭"
}, {
    names: ["art"],
    surrogates: "🎨"
}, {
    names: ["circus_tent"],
    surrogates: "🎪"
}, {
    names: ["microphone"],
    surrogates: "🎤"
}, {
    names: ["headphones"],
    surrogates: "🎧"
}, {
    names: ["musical_score"],
    surrogates: "🎼"
}, {
    names: ["musical_keyboard"],
    surrogates: "🎹"
}, {
    names: ["saxophone"],
    surrogates: "🎷"
}, {
    names: ["trumpet"],
    surrogates: "🎺"
}, {
    names: ["guitar"],
    surrogates: "🎸"
}, {
    names: ["violin"],
    surrogates: "🎻"
}, {
    names: ["clapper"],
    surrogates: "🎬"
}, {
    names: ["video_game"],
    surrogates: "🎮"
}, {
    names: ["space_invader"],
    surrogates: "👾"
}, {
    names: ["dart"],
    surrogates: "🎯"
}, {
    names: ["game_die"],
    surrogates: "🎲"
}, {
    names: ["slot_machine"],
    surrogates: "🎰"
}, {
    names: ["bowling"],
    surrogates: "🎳"
}]
