[{
    names: ["grinning"],
    surrogates: "😀"
}, {
    names: ["grimacing"],
    surrogates: "😬"
}, {
    names: ["grin"],
    surrogates: "😁"
}, {
    names: ["joy"],
    surrogates: "😂"
}, {
    names: ["smiley"],
    surrogates: "😃"
}, {
    names: ["smile"],
    surrogates: "😄"
}, {
    names: ["sweat_smile"],
    surrogates: "😅"
}, {
    names: ["laughing", "satisfied"],
    surrogates: "😆"
}, {
    names: ["innocent"],
    surrogates: "😇"
}, {
    names: ["wink"],
    surrogates: "😉"
}, {
    names: ["blush"],
    surrogates: "😊"
}, {
    names: ["slight_smile"],
    surrogates: "🙂"
}, {
    names: ["upside_down"],
    surrogates: "🙃"
}, {
    names: ["relaxed"],
    surrogates: "☺"
}, {
    names: ["yum"],
    surrogates: "😋"
}, {
    names: ["relieved"],
    surrogates: "😌"
}, {
    names: ["heart_eyes"],
    surrogates: "😍"
}, {
    names: ["kissing_heart"],
    surrogates: "😘"
}, {
    names: ["kissing"],
    surrogates: "😗"
}, {
    names: ["kissing_smiling_eyes"],
    surrogates: "😙"
}, {
    names: ["kissing_closed_eyes"],
    surrogates: "😚"
}, {
    names: ["stuck_out_tongue_winking_eye"],
    surrogates: "😜"
}, {
    names: ["stuck_out_tongue_closed_eyes"],
    surrogates: "😝"
}, {
    names: ["stuck_out_tongue"],
    surrogates: "😛"
}, {
    names: ["money_mouth"],
    surrogates: "🤑"
}, {
    names: ["nerd"],
    surrogates: "🤓"
}, {
    names: ["sunglasses"],
    surrogates: "😎"
}, {
    names: ["hugging"],
    surrogates: "🤗"
}, {
    names: ["smirk"],
    surrogates: "😏"
}, {
    names: ["no_mouth"],
    surrogates: "😶"
}, {
    names: ["neutral_face"],
    surrogates: "😐"
}, {
    names: ["expressionless"],
    surrogates: "😑"
}, {
    names: ["unamused"],
    surrogates: "😒"
}, {
    names: ["rolling_eyes"],
    surrogates: "🙄"
}, {
    names: ["thinking"],
    surrogates: "🤔"
}, {
    names: ["flushed"],
    surrogates: "😳"
}, {
    names: ["disappointed"],
    surrogates: "😞"
}, {
    names: ["worried"],
    surrogates: "😟"
}, {
    names: ["angry"],
    surrogates: "😠"
}, {
    names: ["rage"],
    surrogates: "😡"
}, {
    names: ["pensive"],
    surrogates: "😔"
}, {
    names: ["confused"],
    surrogates: "😕"
}, {
    names: ["slight_frown"],
    surrogates: "🙁"
}, {
    names: ["frowning2"],
    surrogates: "☹"
}, {
    names: ["persevere"],
    surrogates: "😣"
}, {
    names: ["confounded"],
    surrogates: "😖"
}, {
    names: ["tired_face"],
    surrogates: "😫"
}, {
    names: ["weary"],
    surrogates: "😩"
}, {
    names: ["triumph"],
    surrogates: "😤"
}, {
    names: ["open_mouth"],
    surrogates: "😮"
}, {
    names: ["scream"],
    surrogates: "😱"
}, {
    names: ["fearful"],
    surrogates: "😨"
}, {
    names: ["cold_sweat"],
    surrogates: "😰"
}, {
    names: ["hushed"],
    surrogates: "😯"
}, {
    names: ["frowning"],
    surrogates: "😦"
}, {
    names: ["anguished"],
    surrogates: "😧"
}, {
    names: ["cry"],
    surrogates: "😢"
}, {
    names: ["disappointed_relieved"],
    surrogates: "😥"
}, {
    names: ["sleepy"],
    surrogates: "😪"
}, {
    names: ["sweat"],
    surrogates: "😓"
}, {
    names: ["sob"],
    surrogates: "😭"
}, {
    names: ["dizzy_face"],
    surrogates: "😵"
}, {
    names: ["astonished"],
    surrogates: "😲"
}, {
    names: ["zipper_mouth"],
    surrogates: "🤐"
}, {
    names: ["mask"],
    surrogates: "😷"
}, {
    names: ["thermometer_face"],
    surrogates: "🤒"
}, {
    names: ["head_bandage"],
    surrogates: "🤕"
}, {
    names: ["sleeping"],
    surrogates: "😴"
}, {
    names: ["zzz"],
    surrogates: "💤"
}, {
    names: ["poop", "shit"],
    surrogates: "💩"
}, {
    names: ["smiling_imp"],
    surrogates: "😈"
}, {
    names: ["imp"],
    surrogates: "👿"
}, {
    names: ["japanese_ogre"],
    surrogates: "👹"
}, {
    names: ["japanese_goblin"],
    surrogates: "👺"
}, {
    names: ["skull"],
    surrogates: "💀"
}, {
    names: ["ghost"],
    surrogates: "👻"
}, {
    names: ["alien"],
    surrogates: "👽"
}, {
    names: ["robot"],
    surrogates: "🤖"
}, {
    names: ["smiley_cat"],
    surrogates: "😺"
}, {
    names: ["smile_cat"],
    surrogates: "😸"
}, {
    names: ["joy_cat"],
    surrogates: "😹"
}, {
    names: ["heart_eyes_cat"],
    surrogates: "😻"
}, {
    names: ["smirk_cat"],
    surrogates: "😼"
}, {
    names: ["kissing_cat"],
    surrogates: "😽"
}, {
    names: ["scream_cat"],
    surrogates: "🙀"
}, {
    names: ["crying_cat_face"],
    surrogates: "😿"
}, {
    names: ["pouting_cat"],
    surrogates: "😾"
}, {
    names: ["raised_hands"],
    surrogates: "🙌",
    hasDiversity: !0
}, {
    names: ["clap"],
    surrogates: "👏",
    hasDiversity: !0
}, {
    names: ["wave"],
    surrogates: "👋",
    hasDiversity: !0
}, {
    names: ["thumbsup", "+1"],
    surrogates: "👍",
    hasDiversity: !0
}, {
    names: ["thumbsdown", "-1"],
    surrogates: "👎",
    hasDiversity: !0
}, {
    names: ["punch", "facepunch"],
    surrogates: "👊",
    hasDiversity: !0
}, {
    names: ["fist"],
    surrogates: "✊",
    hasDiversity: !0
}, {
    names: ["v"],
    surrogates: "✌",
    hasDiversity: !0
}, {
    names: ["ok_hand"],
    surrogates: "👌",
    hasDiversity: !0
}, {
    names: ["raised_hand", "hand"],
    surrogates: "✋",
    hasDiversity: !0
}, {
    names: ["open_hands"],
    surrogates: "👐",
    hasDiversity: !0
}, {
    names: ["muscle"],
    surrogates: "💪",
    hasDiversity: !0
}, {
    names: ["pray"],
    surrogates: "🙏",
    hasDiversity: !0
}, {
    names: ["point_up"],
    surrogates: "☝",
    hasDiversity: !0
}, {
    names: ["point_up_2"],
    surrogates: "👆",
    hasDiversity: !0
}, {
    names: ["point_down"],
    surrogates: "👇",
    hasDiversity: !0
}, {
    names: ["point_left"],
    surrogates: "👈",
    hasDiversity: !0
}, {
    names: ["point_right"],
    surrogates: "👉",
    hasDiversity: !0
}, {
    names: ["middle_finger"],
    surrogates: "🖕",
    hasDiversity: !0
}, {
    names: ["hand_splayed"],
    surrogates: "🖐",
    hasDiversity: !0
}, {
    names: ["metal"],
    surrogates: "🤘",
    hasDiversity: !0
}, {
    names: ["vulcan"],
    surrogates: "🖖",
    hasDiversity: !0
}, {
    names: ["writing_hand"],
    surrogates: "✍",
    hasDiversity: !0
}, {
    names: ["nail_care"],
    surrogates: "💅",
    hasDiversity: !0
}, {
    names: ["lips"],
    surrogates: "👄"
}, {
    names: ["tongue"],
    surrogates: "👅"
}, {
    names: ["ear"],
    surrogates: "👂",
    hasDiversity: !0
}, {
    names: ["nose"],
    surrogates: "👃",
    hasDiversity: !0
}, {
    names: ["eye"],
    surrogates: "👁"
}, {
    names: ["eyes"],
    surrogates: "👀"
}, {
    names: ["bust_in_silhouette"],
    surrogates: "👤"
}, {
    names: ["busts_in_silhouette"],
    surrogates: "👥"
}, {
    names: ["speaking_head"],
    surrogates: "🗣"
}, {
    names: ["baby"],
    surrogates: "👶",
    hasDiversity: !0
}, {
    names: ["boy"],
    surrogates: "👦",
    hasDiversity: !0
}, {
    names: ["girl"],
    surrogates: "👧",
    hasDiversity: !0
}, {
    names: ["man"],
    surrogates: "👨",
    hasDiversity: !0
}, {
    names: ["woman"],
    surrogates: "👩",
    hasDiversity: !0
}, {
    names: ["person_with_blond_hair"],
    surrogates: "👱",
    hasDiversity: !0
}, {
    names: ["older_man"],
    surrogates: "👴",
    hasDiversity: !0
}, {
    names: ["older_woman"],
    surrogates: "👵",
    hasDiversity: !0
}, {
    names: ["man_with_gua_pi_mao"],
    surrogates: "👲",
    hasDiversity: !0
}, {
    names: ["man_with_turban"],
    surrogates: "👳",
    hasDiversity: !0
}, {
    names: ["cop"],
    surrogates: "👮",
    hasDiversity: !0
}, {
    names: ["construction_worker"],
    surrogates: "👷",
    hasDiversity: !0
}, {
    names: ["guardsman"],
    surrogates: "💂",
    hasDiversity: !0
}, {
    names: ["spy"],
    surrogates: "🕵",
    hasDiversity: !0
}, {
    names: ["santa"],
    surrogates: "🎅",
    hasDiversity: !0
}, {
    names: ["angel"],
    surrogates: "👼",
    hasDiversity: !0
}, {
    names: ["princess"],
    surrogates: "👸",
    hasDiversity: !0
}, {
    names: ["bride_with_veil"],
    surrogates: "👰",
    hasDiversity: !0
}, {
    names: ["walking"],
    surrogates: "🚶",
    hasDiversity: !0
}, {
    names: ["runner", "running"],
    surrogates: "🏃",
    hasDiversity: !0
}, {
    names: ["dancer"],
    surrogates: "💃",
    hasDiversity: !0
}, {
    names: ["dancers"],
    surrogates: "👯"
}, {
    names: ["couple"],
    surrogates: "👫"
}, {
    names: ["two_men_holding_hands"],
    surrogates: "👬"
}, {
    names: ["two_women_holding_hands"],
    surrogates: "👭"
}, {
    names: ["bow"],
    surrogates: "🙇",
    hasDiversity: !0
}, {
    names: ["information_desk_person"],
    surrogates: "💁",
    hasDiversity: !0
}, {
    names: ["no_good"],
    surrogates: "🙅",
    hasDiversity: !0
}, {
    names: ["ok_woman"],
    surrogates: "🙆",
    hasDiversity: !0
}, {
    names: ["raising_hand"],
    surrogates: "🙋",
    hasDiversity: !0
}, {
    names: ["person_with_pouting_face"],
    surrogates: "🙎",
    hasDiversity: !0
}, {
    names: ["person_frowning"],
    surrogates: "🙍",
    hasDiversity: !0
}, {
    names: ["haircut"],
    surrogates: "💇",
    hasDiversity: !0
}, {
    names: ["massage"],
    surrogates: "💆",
    hasDiversity: !0
}, {
    names: ["couple_with_heart"],
    surrogates: "💑"
}, {
    names: ["couple_ww"],
    surrogates: "👩‍❤️‍👩"
}, {
    names: ["couple_mm"],
    surrogates: "👨‍❤️‍👨"
}, {
    names: ["couplekiss"],
    surrogates: "💏"
}, {
    names: ["kiss_ww"],
    surrogates: "👩‍❤️‍💋‍👩"
}, {
    names: ["kiss_mm"],
    surrogates: "👨‍❤️‍💋‍👨"
}, {
    names: ["family"],
    surrogates: "👪"
}, {
    names: ["family_mwg"],
    surrogates: "👨‍👩‍👧"
}, {
    names: ["family_mwgb"],
    surrogates: "👨‍👩‍👧‍👦"
}, {
    names: ["family_mwbb"],
    surrogates: "👨‍👩‍👦‍👦"
}, {
    names: ["family_mwgg"],
    surrogates: "👨‍👩‍👧‍👧"
}, {
    names: ["family_wwb"],
    surrogates: "👩‍👩‍👦"
}, {
    names: ["family_wwg"],
    surrogates: "👩‍👩‍👧"
}, {
    names: ["family_wwgb"],
    surrogates: "👩‍👩‍👧‍👦"
}, {
    names: ["family_wwbb"],
    surrogates: "👩‍👩‍👦‍👦"
}, {
    names: ["family_wwgg"],
    surrogates: "👩‍👩‍👧‍👧"
}, {
    names: ["family_mmb"],
    surrogates: "👨‍👨‍👦"
}, {
    names: ["family_mmg"],
    surrogates: "👨‍👨‍👧"
}, {
    names: ["family_mmgb"],
    surrogates: "👨‍👨‍👧‍👦"
}, {
    names: ["family_mmbb"],
    surrogates: "👨‍👨‍👦‍👦"
}, {
    names: ["family_mmgg"],
    surrogates: "👨‍👨‍👧‍👧"
}, {
    names: ["womans_clothes"],
    surrogates: "👚"
}, {
    names: ["shirt", "tshirt"],
    surrogates: "👕"
}, {
    names: ["jeans"],
    surrogates: "👖"
}, {
    names: ["necktie"],
    surrogates: "👔"
}, {
    names: ["dress"],
    surrogates: "👗"
}, {
    names: ["bikini"],
    surrogates: "👙"
}, {
    names: ["kimono"],
    surrogates: "👘"
}, {
    names: ["lipstick"],
    surrogates: "💄"
}, {
    names: ["kiss"],
    surrogates: "💋"
}, {
    names: ["footprints"],
    surrogates: "👣"
}, {
    names: ["high_heel"],
    surrogates: "👠"
}, {
    names: ["sandal"],
    surrogates: "👡"
}, {
    names: ["boot"],
    surrogates: "👢"
}, {
    names: ["mans_shoe", "shoe"],
    surrogates: "👞"
}, {
    names: ["athletic_shoe"],
    surrogates: "👟"
}, {
    names: ["womans_hat"],
    surrogates: "👒"
}, {
    names: ["tophat"],
    surrogates: "🎩"
}, {
    names: ["helmet_with_cross"],
    surrogates: "⛑"
}, {
    names: ["mortar_board"],
    surrogates: "🎓"
}, {
    names: ["crown"],
    surrogates: "👑"
}, {
    names: ["school_satchel"],
    surrogates: "🎒"
}, {
    names: ["pouch"],
    surrogates: "👝"
}, {
    names: ["purse"],
    surrogates: "👛"
}, {
    names: ["handbag"],
    surrogates: "👜"
}, {
    names: ["briefcase"],
    surrogates: "💼"
}, {
    names: ["eyeglasses"],
    surrogates: "👓"
}, {
    names: ["dark_sunglasses"],
    surrogates: "🕶"
}, {
    names: ["ring"],
    surrogates: "💍"
}, {
    names: ["closed_umbrella"],
    surrogates: "🌂"
}]
