name: Label Specification

on:
  workflow_dispatch:
  label:
    types: [created, edited, deleted]

jobs:
  label-spec:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/TSLedger/.github/refs/heads/main/.github/spec/label.yml
          delete-other-labels: true
          token: ${{ secrets.GITHUB_TOKEN }}
